apiVersion: v1
kind: ConfigMap
metadata:
  namespace: openshift-etcd-operator
  name: etcd-operator-config
data:
  config.yaml: |
    apiVersion: operator.openshift.io/v1alpha1
    kind: GenericOperatorConfig
