apiVersion: apps/v1
kind: Deployment
metadata:
  name: openshift-etcd-quorum-guard
  namespace: openshift-etcd
  annotations:
    exclude.release.openshift.io/internal-openshift-hosted: "true"
spec:
  replicas: 3
  selector:
    matchLabels:
      k8s-app: openshift-etcd-quorum-guard
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: openshift-etcd-quorum-guard
        k8s-app: openshift-etcd-quorum-guard
    spec:
      hostNetwork: true
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: k8s-app
                operator: In
                values:
                - "openshift-etcd-quorum-guard"
            topologyKey: kubernetes.io/hostname
      nodeSelector:
        node-role.kubernetes.io/master: ""
      priorityClassName: "system-cluster-critical"
      terminationGracePeriodSeconds: 3
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
        operator: Exists
      - key: node.kubernetes.io/not-ready
        effect: NoExecute
        operator: Exists
        tolerationSeconds: 120
      - key: node.kubernetes.io/unreachable
        effect: NoExecute
        operator: Exists
        tolerationSeconds: 120
      - key: node-role.kubernetes.io/etcd
        operator: Exists
        effect: NoSchedule
      containers:
      - image: quay.io/openshift/origin-cli:latest
        imagePullPolicy: IfNotPresent
        name: guard
        terminationMessagePolicy: FallbackToLogsOnError
        volumeMounts:
        - mountPath: /var/run/secrets/etcd-client
          name: etcd-client
        - mountPath: /var/run/configmaps/etcd-serving-ca
          name: etcd-serving-ca
        command:
        - /bin/bash
        args:
        - -c
        - |
          # properly handle TERM and exit as soon as it is signaled
          set -euo pipefail
          trap 'jobs -p | xargs -r kill; exit 0' TERM
          sleep infinity & wait
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - |
                declare -r croot=/var/run
                declare -r health_endpoint="https://127.0.0.1:2379/health"
                declare -r key="$croot/secrets/etcd-client/tls.key"
                declare -r cert="$croot/secrets/etcd-client/tls.crt"
                declare -r cacert="$croot/configmaps/etcd-serving-ca/ca-bundle.crt"
                export NSS_SDB_USE_CACHE=no
                [[ -z $cert || -z $key ]] && exit 1
                curl --max-time 2 --silent --cert "$cert" --key "$key" --cacert "$cacert" "$health_endpoint" |grep '{ *"health" *: *"true" *}'
            initialDelaySecond: 5
            periodSecond: 5
        resources:
          requests:
            cpu: 10m
            memory: 5Mi
      volumes:
      - name: etcd-client
        secret:
          secretName: etcd-client
      - name: etcd-serving-ca
        configMap:
          name: etcd-serving-ca
