apiVersion: v1
kind: ConfigMap
metadata:
  # this CA bundle holds the values for trusting the bootstrap etcd
  name: initial-etcd-ca
  namespace: openshift-config
data:
  ca-bundle.crt: |
    {{ .Assets | load "kube-ca.crt" | indent 4 }}

