apiVersion: v1
kind: Secret
metadata:
  name: controller-manager-kubeconfig
  namespace: openshift-etcd
  labels:
    tier: "control-plane"
    k8s-app: "etcd"
    openshift.io/control-plane: "true"
    openshift.io/component: "controller"
data:
  kubeconfig: {{ .Assets | load "kubeconfig" | base64 }}
